version: "3"

services:
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  checkout:
    image: "mchenachi/microsservice-avancadev-checkout"
    ports:
      - "9090:9090"
  payment:
    image: "mchenachi/microsservice-avancadev-payment"
    ports:
      - "9091:9091"
  coupon:
    image: "mchenachi/microsservice-avancadev-coupon"
    ports:
      - "9092:9092"
